### ISSUE TITLE
你好运行项目报错

### ISSUE THREAD

**Issue by JserJser** [wkl007/GitHubPopular#2]
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening GitHubPopular.xcodeproj

** BUILD FAILED **

The following commands produced analyzer issues:
	517box/GitHubPopular/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64
	Analyze /Users/517box/GitHubPopular/node_modules/react-native/React/Base/RCTModuleMethod.mm normal x86_64
(2 commands with analyzer issues)

The following build commands failed:
	Ld /Users/517box/GitHubPopular/ios/build/GitHubPopular/Build/Products/Debug-iphonesimulator/GitHubPopular.app/GitHubPopular normal x86_64
(1 failure)

**Comment by wkl007** [comment]
抱歉，项目没有适配ios
